import { Event } from "../models/Event";
import { EventAmount } from "../models/EventAmount";

export const MOCK_EVENTS: Event[] = [
  {
    id: "2",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Art",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "3",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Circus",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "4",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Disco",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "6",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Festival",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "7",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Food",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "8",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Live",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "6",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Museum",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "9",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Science",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "10",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Sport",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "11",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Theatre",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "11",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Outdoor",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "11",
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Cinema",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
];

export const MOCK_EVENTS_AMOUNT: EventAmount[] = [
  {
    id: "2",
    amount: 2,
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Festival",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "3",
    amount: 3,
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Festival",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "4",
    amount: 1,
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Festival",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
  {
    id: "226",
    amount: 3,
    version: 1,
    phone: "0984252265",
    price: 43,
    title: "Strike",
    owner_name: "BSide",
    location: "Via Guglielmo Marconi, 32, 87036 Quattromiglia CS, Italy",
    category: "Live",
    description:
      "Rappresentazione dell'opera di Luce Plamondon. Ingresso gratuito offerto dall'Unical per studenti e non.",
    opening: new Date(),
    ending: new Date(),
    longitude: 22.22,
    latitude: 11.22,
    total_posts: 40,
    remaining_posts: 22,
  },
];
export const DATA: any = {
  categories: [
    {
      categori_id: 1,
      name: "drinks",
    },
    {
      categori_id: 2,
      name: "lunch",
    },
    {
      categori_id: 3,
      name: "food",
    },
    {
      categori_id: 4,
      name: "sea",
    },
  ],
  events: [
    {
      id: 1,
      title: "Lorem",
      price: "60.000",
      available: true,
      best_seller: true,
      categories: [1, 4],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 2,
      title: "ipsum",
      price: "20.000",
      available: false,
      best_seller: false,
      categories: [4],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 3,
      title: "dolor",
      price: "10.000",
      available: true,
      best_seller: true,
      categories: [4],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 4,
      title: "sit",
      price: "35.000",
      available: false,
      best_seller: false,
      categories: [1, 2],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 5,
      title: "amet",
      price: "12.000",
      available: true,
      best_seller: true,
      categories: [1, 4],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 6,
      title: "consectetur",
      price: "120.000",
      available: true,
      best_seller: false,
      categories: [1, 4],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 7,
      title: "adipiscing",
      price: "50.000",
      available: false,
      best_seller: false,
      categories: [1, 3],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 8,
      title: "elit",
      price: "2000",
      available: true,
      best_seller: false,
      categories: [1, 3],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 9,
      title: "Maecenas",
      price: "150.000",
      available: true,
      best_seller: true,
      categories: [2, 4],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
    {
      id: 10,
      title: "eu",
      price: "200.000",
      available: false,
      best_seller: true,
      categories: [2, 3],
      img: "http://lorempixel.com/200/100/food/",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eu.",
    },
  ],
};
